project:
  type: book
  output-dir: ../docs/pyschool2025  # para que lo deje en docs/pyschool2025

  
book:
  title: "ğŸ PySchool"
  author: "Python Chile"
  date: "05/30/2025"
  favicon: "images/pc.png"
  repo-url: "https://github.com/fralfaro/pyschool"

  chapters:
    - index.qmd

    - part: ğŸ¯ Talleres
      chapters:
        - material/taller/intro.qmd
        - material/taller/taller_1.qmd
        - material/taller/taller_2.qmd

    - part: ğŸ“œ Anexos
      chapters:
        - material/anexos/cierre_evento.qmd
        - material/anexos/autoria.qmd


lang: es

format:
  html:
    theme: flatly
    number-sections: false
    toc: false
    page-layout: full
  epub:
    cover-image: images/cover.png


filters: 
  - pyodide

