# Project Configuration
project:
  type: book
  output-dir: "../docs"
  
book:
  title: "Escape Rooms"
  author: 
    - "Francisco Alfaro"
    - "Valeska Canales"
  date: "10/07/2025"
  favicon: "images/favicon.png"
  repo-url: "https://github.com/fralfaro/escape_rooms"

  chapters:
    - index.qmd
    - students.qmd
    - part: Estaci√≥n Espacial üõ∞Ô∏è
      chapters:
        - taller1/taller1.qmd
        - taller1/rooms/0.qmd
        - taller1/rooms/1.qmd
        - taller1/rooms/2.qmd
        - taller1/rooms/3.qmd
        - taller1/rooms/4.qmd
        - taller1/rooms/5.qmd
        - taller1/rooms/6.qmd
        - taller1/rooms/end.qmd
    - part: Laboratorio Pokemon üß™
      chapters:
        - taller2/taller2.qmd
        - taller2/rooms/0.qmd
        - taller2/rooms/1.qmd
        - taller2/rooms/2.qmd
        - taller2/rooms/3.qmd
        - taller2/rooms/4.qmd
        - taller2/rooms/end.qmd

    - part: Anexos üìö
      chapters:
        - intro.qmd
        - teachers.qmd
        - anexos/cierre_evento.qmd
        - anexos/autoria.qmd


lang: es

format:
  html:
    theme: sketchy
    css: "style.css"
    number-sections: false
    toc: false
    page-navigation: false


# Extensions
filters: 
  - pyodide
