# Project Configuration
project:
  type: book
  output-dir: "../docs"
  
book:
  title: "ğŸ PySchool"
  author: "Python Chile"
  date: "05/30/2025"
  favicon: "images/pc.png"
  repo-url: "https://github.com/fralfaro/pyschool"

  chapters:
    - index.qmd
    - intro.qmd
    - part: ğŸ¯ Python BÃ¡sico
      chapters:
        - taller1/taller1.qmd
        - taller1/rooms/0.qmd
        - taller1/rooms/1.qmd
        - taller1/rooms/2.qmd
        - taller1/rooms/3.qmd
        - taller1/rooms/4.qmd
        - taller1/rooms/5.qmd
        - taller1/rooms/6.qmd
        - taller1/rooms/end.qmd
    - part: ğŸ¯ Ciencia de datos
      chapters:
        - taller2/taller2.qmd
        - taller2/rooms/0.qmd
        - taller2/rooms/1.qmd
        - taller2/rooms/2.qmd
        - taller2/rooms/end.qmd

    - part: ğŸ“œ Anexos
      chapters:
        - anexos/cierre_evento.qmd
        - anexos/autoria.qmd

lang: es

format:
  html:
    theme: sketchy
    css: "style.css"
    number-sections: false
    toc: false
    page-layout: full
  epub:
    cover-image: images/cover.png

# Extensions
filters: 
  - pyodide
